twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # Créer une variable globale qui sera accessible dans toutes les pages
    globals:
        openTime: '@App\Twig\OpenTimeExtension'

when@test:
    twig:
        strict_variables: true
